### ISSUE TITLE
apex Gradient overflow. 

### ISSUE THREAD

**Issue by reroze** [xuewyang/JoGANIC#5]
I've trained joganic model without apex with small bsz. But it takes long time and only get 4.64 Belu. So I guess I have to train model with apex.
But every time I use apex, it always cause Gradient overflow after 50~55 epoch.

```
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 0.5
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 0.25
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 0.125
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 0.0625
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 0.03125
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 0.015625
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 0.0078125
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 0.00390625
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 0.001953125
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 0.0009765625
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 0.00048828125
```

And then I got nan loss for caption, I don't change any code from github, and I use the file in scripts to obtain data, I use the same config with Transform-and-tell. I checked the data is clean. Have you met the same problem during training stage? Could you give me some advice to fix it?

**Comment by xuewyang** [comment]
Sorry that you met this problem. I think I had this problem before but I don't remember how I fixed it. I really don't have time to look into this problem. Sorry that you have to rely on yourself.
